export enum InviteType{
    FRIENDSHIP = 'FRIENDSHIP',
    GROUP_REQUEST = 'GROUP_REQUEST',
    GROUP_INVITATION = 'GROUP_INVITATION',
    GOAL_REQUEST = "GOAL_REQUEST",
    GOAL_INVITATION = "GOAL_INVITATION"
}